version: '3'

services:
  api:
    image: api
    build: 
      context: .
      dockerfile: Dockerfile
    ports: ["7001:7001"]
    depends_on:
      - migration
    
  migration:
    image: migration
    build: 
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres